### ISSUE TITLE
Problem of the rendered image

### ISSUE THREAD

**Issue by sonnefred** [carlinds/unisim#3]
Hi, I'm trying to train a  model using unisim plug-in, in the tensorboard, the rendered image is like this, which is very weird ... Do you know what causes this? Thanks.
![图片](https://github.com/carlinds/unisim/assets/66628395/6bf2fea5-02c5-4210-8baf-c11ef3c751ab)

**Comment by carlinds** [comment]
Unisim is trained in multiple stages. In the first stage, the CNN decoder is frozen so the image you showed looks like expected. Let the model train until the second stage and you should start to see more sensible renderings.

**Comment by sonnefred** [comment]
> Unisim is trained in multiple stages. In the first stage, the CNN decoder is frozen so the image you showed looks like expected. Let the model train until the second stage and you should start to see more sensible renderings.

OK, thanks for your reply.
